// this is the page where I write reviews

const books = [
{ 
    slug: "the-answer-is-no",
    title: "The Answer Is No",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2024,
    pages: 68,
    coverImage: "https://covers.openlibrary.org/b/isbn/1662526520.jpg",
    review: ["This is my first book by Fredrik Backman. I had not heard about him before. I picked it up only because it was on Kindle Unlimited and was looking for a quick read. But how would I know what I was in for?
              
            Those sixty pages of humour, wisdom and the sharp observation of human psychology hooked me with the author for life.
            
            Being smart is the worst thing one can be in modern society. All it ever means is more work.

            The novella explores boundaries, personal space and our relationship with the word “no”. It is about a man who doesn’t want to engage with anyone, wants to be left on his own. But does the society let him? Of course, not.
          
            He is, without his intention, gets dragged into a task of the housing society he lives in. He tries his best to get out of it, only to be dragged more.
          
            The story portrays how we are torn between the societal pressures and our own needs; how difficult it is to say “no” and the conflict we bear inside. Backman tells this deeply human story with a blend of humour, introspecting every now and then, which I have come to know as his signature style.
          
            Though it was a quick read, it left a lasting impression on me, not only about the author, but also the topic of self-assertion.
          ]  
  },
  {
    slug: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self Help",
    rating: 4.8,
    published: 2018,
    pages: 320,
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    review: "An extraordinarily practical guide on how small daily changes compound into massive personal transformations over time.",
  },
  {
    slug: "mother-mary-comes-to-me",
    title: "Mother Mary Comes To Me",
    author: "Arundhati Roy",
    genre: "Memoir",
    rating: 4.5,
    published: 2025,
    pages: 224,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780241761724.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "beartown",
    title: "Beartown",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2017,
    pages: 432,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781410498120.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "on-earth-we-are-briefly-gorgeous",
    title: "On Earth We Are Briefly Gorgeous",
    author: "Ocean Vuong",
    genre: "Fiction",
    rating: 4.5,
    published: 2019,
    pages: 256,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781473564473.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "the-forty-rules-of-love",
    title: "The Forty Rules of Love",
    author: "Elif Shafak",
    genre: "Fiction",
    rating: 4.5,
    published: 2015,
    pages: 368,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780241972939.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "the-beekeeper-of-aleppo",
    title: "The Beekeeper of Aleppo",
    author: "Christy Lefteri",
    genre: "Fiction",
    rating: 4.5,
    published: 2017,
    pages: 311,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781984821218.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
    {
    slug: "the-summer-i-turned-pretty",
    title: "The Summer I Turned Pretty",
    author: "Jenny Han",
    genre: "Fiction",
    rating: 4.5,
    published: 2014,
    pages: 276,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780141353821.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "us-against-you",
    title: "Us Against You",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2018,
    pages: 435,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781501160790.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
    {
    slug: "from-goddess-to-mortal",
    title: "From Goddess To Mortal",
    author: "Rashmila Shakya - As Told to Scott Berry",
    genre: "Memoir",
    rating: 4.5,
    published: 2007,
    pages: 152,
    coverImage: "https://covers.openlibrary.org/b/isbn/9789994678808.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
    {
    slug: "evidence-of-the-affair",
    title: "Evidence of the Affair",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    rating: 4.5,
    published: 2018,
    pages: 88,
    coverImage: "https://covers.openlibrary.org/b/isbn/9789026356018.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "britt-marie-was-here",
    title: "Britt-Marie Was Here",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2016,
    pages: 324,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781501142543.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "the-woman-in-the-cabin",
    title: "The Woman In The Cabin",
    author: "Becca Day",
    genre: "Fiction",
    rating: 4.5,
    published: 2024,
    pages: 3,
    coverImage: "https://covers.openlibrary.org/b/isbn/00.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  {
    slug: "my-evil-mother",
    title: "My Evil Mother",
    author: "Margaret Atwood",
    genre: "Fiction",
    rating: 4.5,
    published: 2022,
    pages: 3,
    coverImage: "https://covers.openlibrary.org/b/isbn/OL37934405M.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "the-bookstore-sisters",
    title: "The Bookstore Sisters",
    author: "Alice Hoffman",
    genre: "Fiction",
    rating: 4.5,
    published: 2017,
    pages: 3,
    coverImage: "https://covers.openlibrary.org/b/isbn/00.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "the-wrong-daughter",
    title: "The Wrong Daughter",
    author: "Dandy Smith",
    genre: "Fiction",
    rating: 4.5,
    published: 20,
    pages: 3,
    coverImage: "https://covers.openlibrary.org/b/isbn/xx.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "my-friends",
    title: "My Friends",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2025,
    pages: 436,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781982121655.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "a-man-called-ove",
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    genre: "Fiction",
    rating: 4.5,
    published: 2012,
    pages: 477,
    coverImage: "https://covers.openlibrary.org/b/isbn/9781410472922.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "the-dutch-house",
    title: "The Dutch House",
    author: "Ann Patchett",
    genre: "Fiction",
    rating: 4.5,
    published: 2019,
    pages: 354,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062972149.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "commonwealth",
    title: "Commonwealth",
    author: "Ann Patchett",
    genre: "Fiction",
    rating: 4.5,
    published: 2016,
    pages: 322,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062491794.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  },
  { 
    slug: "tom-lake",
    title: "Tom Lake",
    author: "Ann Patchett",
    genre: "Fiction",
    rating: 4.5,
    published: 2023,
    pages: 352,
    coverImage: "https://covers.openlibrary.org/b/isbn/9780063327528.jpg",
    review: "A deeply personal and evocative memoir that reflects on family, identity, and memory.A deeply personal and evocative memoir that reflects on family, identity, and memory.",
  }



];